In [1]:
import numpy as np
import pandas as pd
import financedatabase as fd

In [2]:
indices = fd.Indices()

In [3]:
ind_info = indices.select()

In [4]:
ind_info['exchange'].unique()

<ArrowStringArray>
['SHH', 'ZRH',   nan, 'GER', 'STU', 'PAR', 'TLV', 'SHZ', 'AMS', 'FGI', 'FSI',
 'VIE', 'BRU', 'EBS', 'MCX', 'PHS', 'BSE', 'ATH', 'CSE', 'MEX', 'MCE', 'ENX',
 'SAO', 'TAI', 'JKT', 'IST', 'LIS', 'TWO', 'HKG', 'TSI', 'NYB', 'PRA', 'SES',
 'MIL', 'NZE', 'BUE', 'NIM', 'CCS', 'KSC', 'NSI', 'CAI', 'OSL', 'SGO', 'DJI',
 'ASE', 'NYS', 'SNP', 'ASX', 'SET', 'WCB', 'RIS', 'BUD', 'STO', 'DOH', 'ISE',
 'JNB', 'KLS', 'KOE', 'OSA', 'SAU', 'TAL', 'LIT', 'VAN', 'OPI']
Length: 64, dtype: str

In [5]:
ind_info[ind_info['exchange'] == 'SNP']

,name,currency,summary,category_group,category,exchange,mic
symbol,,,,,,,
^AEDW,Alerian Midstream Energy Divide,USD,The Alerian Midstream Energy Dividend Index is...,Energy,Energy,SNP,NaN
^AEDWN,Alerian Midstream Energy Divide,USD,The Alerian Midstream Energy Dividend Index is...,Energy,Energy,SNP,NaN
^AEDWT,Alerian Midstream Energy Divide,USD,The Alerian Midstream Energy Dividend Index is...,Energy,Energy,SNP,NaN
^AEIPR,American Energy Independence Pr,USD,NaN,Energy,Energy,SNP,NaN
^AEITR,American Energy Independence To,USD,NaN,Energy,Energy,SNP,NaN
...,...,...,...,...,...,...,...
^WTJSE,WisdomTree Japan SmallCap Equit,USD,The WisdomTree Japan SmallCap Equity Index is ...,Equities,Small Cap,SNP,NaN
^WTJSEH,WisdomTree Japan Hedged SmallCa,USD,The WisdomTree Japan Hedged SmallCap Equity In...,Equities,Small Cap,SNP,NaN
^WTUKEB,WisdomTree UK Equity Income Ind,GBP,NaN,Equities,NaN,SNP,NaN
^YLDX300,NaN,USD,NaN,NaN,NaN,SNP,NaN
^YLDX400,NaN,USD,NaN,NaN,NaN,SNP,NaN

In [6]:
equities = fd.Equities()

In [8]:
equities.show_options()

{'currency': <ArrowStringArray>
 ['ARS', 'AUD', 'BRL', 'CAD', 'CHF', 'CLP', 'CNY', 'COP', 'CZK', 'DKK', 'EUR',
  'GBP', 'HKD', 'HUF', 'IDR', 'ILA', 'ILS', 'INR', 'ISK', 'JPY', 'KES', 'KRW',
  'LKR', 'MXN', 'MYR', 'NOK', 'NZD', 'PEN', 'PHP', 'PLN', 'QAR', 'RUB', 'SAR',
  'SEK', 'SGD', 'THB', 'TRY', 'TWD', 'USD', 'ZAC', 'ZAR']
 Length: 41, dtype: str,
 'sector': <ArrowStringArray>
 ['Communication Services', 'Consumer Discretionary',       'Consumer Staples',
                  'Energy',             'Financials',            'Health Care',
             'Industrials', 'Information Technology',              'Materials',
             'Real Estate',              'Utilities']
 Length: 11, dtype: str,
 'industry_group': <ArrowStringArray>
 [                      'Automobiles & Components',
                                           'Banks',
                                   'Capital Goods',
              'Commercial & Professional Services',
                     'Consumer Durables & Apparel',
                               'Consumer Services',
                          'Diversified Financials',
                                          'Energy',
                        'Food & Staples Retailing',
                        'Food, Beverage & Tobacco',
                'Health Care Equipment & Services',
                   'Household & Personal Products',
                                       'Insurance',
                                       'Materials',
                           'Media & Entertainment',
  'Pharmaceuticals, Biotechnology & Life Sciences',
                                     'Real Estate',
                                       'Retailing',
        'Semiconductors & Semiconductor Equipment',
                             'Software & Services',
                 'Technology Hardware & Equipment',
                      'Telecommunication Services',
                                  'Transportation',
                                       'Utilities']
 Length: 24, dtype: str,
 'industry': <ArrowStringArray>
 [                                  'Aerospace & Defense',
                                'Air Freight & Logistics',
                                               'Airlines',
                                        'Auto Components',
                                            'Automobiles',
                                                  'Banks',
                                              'Beverages',
                                          'Biotechnology',
                                      'Building Products',
                                        'Capital Markets',
                                              'Chemicals',
                         'Commercial Services & Supplies',
                               'Communications Equipment',
                             'Construction & Engineering',
                                 'Construction Materials',
                                       'Consumer Finance',
                                 'Containers & Packaging',
                                           'Distributors',
                          'Diversified Consumer Services',
                         'Diversified Financial Services',
                 'Diversified Telecommunication Services',
                                     'Electric Utilities',
                                   'Electrical Equipment',
         'Electronic Equipment, Instruments & Components',
                            'Energy Equipment & Services',
                                          'Entertainment',
           'Equity Real Estate Investment Trusts (REITs)',
                               'Food & Staples Retailing',
                                          'Food Products',
                                          'Gas Utilities',
                       'Health Care Equipment & Supplies',
                       'Health Care Providers & Services',
                                 'Health Care Technology',
                          'Hotels, Restaurants & Leisure',
                                     'Household Durables',
                                     'Household Products',
                                            'IT Services',
  'Independent Power and Renewable Electricity Producers',
                               'Industrial Conglomerates',
                                              'Insurance',
                           'Interactive Media & Services',
                     'Internet & Direct Marketing Retail',
                                       'Leisure Products',
                         'Life Sciences Tools & Services',
                                              'Machinery',
                                                 'Marine',
                                                  'Media',
                                        'Metals & Mining',
                                        'Multi-Utilities',
                                       'Multiline Retail',
                            'Oil, Gas & Consumable Fuels',
                                'Paper & Forest Products',
                                      'Personal Products',
                                        'Pharmaceuticals',
                                  'Professional Services',
                   'Real Estate Management & Development',
                                            'Road & Rail',
               'Semiconductors & Semiconductor Equipment',
                                               'Software',
                                       'Specialty Retail',
             'Technology Hardware, Storage & Peripherals',
                       'Textiles, Apparel & Luxury Goods',
                             'Thrifts & Mortgage Finance',
                                                'Tobacco',
                       'Trading Companies & Distributors',
                          'Transportation Infrastructure',
                                        'Water Utilities',
                    'Wireless Telecommunication Services']
 Length: 68, dtype: str,
 'exchange': <ArrowStringArray>
 ['AMS', 'AQS', 'ASE', 'ASX', 'ATH', 'BER', 'BRU', 'BSE', 'BTS', 'BUD', 'BUE',
  'CAI', 'CCS', 'CNQ', 'CPH', 'CSE', 'DOH', 'DUS', 'EBS', 'ENX', 'FKA', 'FRA',
  'GER', 'HAM', 'HAN', 'HEL', 'HKG', 'ICE', 'IOB', 'ISE', 'IST', 'JKT', 'JNB',
  'JPX', 'KLS', 'KOE', 'KSC', 'LIS', 'LIT', 'LSE', 'MCE', 'MCX', 'MEX', 'MIL',
  'MUN', 'NAE', 'NCM', 'NEO', 'NGM', 'NMS', 'NSE', 'NSI', 'NYQ', 'NZE', 'OBB',
  'OEM', 'OID', 'OQB', 'OQX', 'OSL', 'PAR', 'PCX', 'PNK', 'PRA', 'RIS', 'SAO',
  'SAP', 'SAT', 'SAU', 'SES', 'SET', 'SGO', 'SHH', 'SHZ', 'STO', 'STU', 'TAI',
  'TAL', 'TLO', 'TLV', 'TOR', 'TWO', 'VAN', 'VIE']
 Length: 84, dtype: str,
 'mic': <ArrowStringArray>
 ['AQXE', 'ARCX', 'ASEX', 'BATS', 'BVCA', 'BVMF', 'DSMD', 'MISX', 'NEOE',
  'OTCM', 'ROCO', 'XAMS', 'XASE', 'XASX', 'XBER', 'XBKK', 'XBOM', 'XBRU',
  'XBUD', 'XBUE', 'XCAI', 'XCNQ', 'XCOL', 'XCSE', 'XDUB', 'XDUS', 'XETR',
  'XFKA', 'XFRA', 'XHAM', 'XHAN', 'XHEL', 'XHKG', 'XICE', 'XIDX', 'XIST',
  'XJPX', 'XJSE', 'XKLS', 'XKOS', 'XKRX', 'XLIS', 'XLIT', 'XLON', 'XMAD',
  'XMEX', 'XMIL', 'XMUN', 'XNAS', 'XNSE', 'XNYS', 'XNZE', 'XOSL', 'XPAR',
  'XPRA', 'XRIS', 'XSAP', 'XSAU', 'XSES', 'XSGO', 'XSHE', 'XSHG', 'XSTO',
  'XSTU', 'XSWX', 'XTAE', 'XTAI', 'XTAL', 'XTSE', 'XTSX', 'XWBO']
 Length: 71, dtype: str,
 'market': <ArrowStringArray>
 [      'Aequitas NEO Exchange (Lit Book)',
                            'Aktie Torget',
                          'Aquis Exchange',
                   'Athens Stock Exchange',
          'Australian Securities Exchange',
                       'BATS BZX Exchange',
                               'BSE India',
                            'BX Worldcaps',
                   'Berlin Stock Exchange',
             'Bolsa De Valores De Caracas',
  'Bolsa de Comercio de Santiago de Chile',
                          'Borsa Istanbul',
                          'Borsa Italiana',
                            'Bovespa Soma',
                 'Budapest Stock Exchange',
         'Buenos Aires Mercato De Valores',
                          'Bursa Malaysia',
            'Canadian Securities Exchange',
                  'Colombo Stock Exchange',
               'Dusseldorf Stock Exchange',
                       'Egyptian Exchange',
                                 'EuroTLX',
                                'Euronext',
                      'Euronext Amsterdam',
                       'Euronext Brussels',
                         'Euronext Lisbon',
                          'Euronext Paris',
                'Frankfurt Stock Exchange',
                  'Fukuoka Stock Exchange',
                  'Hamburg Stock Exchange',
                  'Hanover Stock Exchange',
                'Hong Kong Stock Exchange',
                'Indonesia Stock Exchange',
                    'Irish Stock Exchange',
             'Johannesburg Stock Exchange',
                                   'KONEX',
                      'KOSPI Stock Market',
     'London Stock Exchange (OTC and ITR)',
   'London Stock Exchange (international)',
                   'Mexico Stock Exchange',
                 'Moscow Exchange - MICEX',
                   'Munich Stock Exchange',
                   'NASDAQ Capital Market',
                    'NASDAQ Global Select',
                          'NASDAQ Iceland',
                     'NASDAQ OMX Helsinki',
                         'NASDAQ OMX Riga',
                    'NASDAQ OMX Stockholm',
                      'NASDAQ OMX Tallinn',
                      'NASDAQ OMX Vilnius',
                               'NYSE Arca',
                                'NYSE MKT',
                       'Nasdaq Copenhagen',
        'National Stock Exchange of India',
                 'New York Stock Exchange',
                    'New Zealand Exchange',
                    'Nordic Growth Market',
                      'OTC Bulletin Board',
                               'Oslo Bors',
                   'Prague Stock Exchange',
                          'Qatar Exchange',
             'Sapporo Securities Exchange',
            'Saudi Arabian Stock Exchange',
                 'Shanghai Stock Exchange',
                 'Shenzhen Stock Exchange',
                      'Singapore Exchange',
               'Sociedad de Bolsas (SIBE)',
                'Stuttgart Stock Exchange',
                    'TSX Toronto Exchange',
                    'TSX Venture Exchange',
                   'Taipei Stock Exchange',
                   'Taiwan Stock Exchange',
                 'Tel Aviv Stock Exchange',
          'The Stock Exchange of Thailand',
                    'Tokyo Stock Exchange',
                   'Vienna Stock Exchange',
                                   'XETRA',
                             'us24_market',
                               'us_market']
 Length: 79, dtype: str,
 'country': <ArrowStringArray>
 [         'Afghanistan',             'Anguilla',            'Argentina',
             'Australia',              'Austria',           'Azerbaijan',
               'Bahamas',           'Bangladesh',             'Barbados',
               'Belgium',
  ...
              'Thailand',               'Turkey',  'U.S. Virgin Islands',
               'Ukraine', 'United Arab Emirates',       'United Kingdom',
         'United States',              'Uruguay',              'Vietnam',
                'Zambia']
 Length: 114, dtype: str,
 'market_cap': <ArrowStringArray>
 ['Large Cap', 'Mega Cap', 'Micro Cap', 'Mid Cap', 'Nano Cap', 'Small Cap']
 Length: 6, dtype: str}

In [11]:
equity_sample = equities.select()

In [13]:
len(equity_sample)

151074

In [16]:
equity_sample[equity_sample['market'] == 'New York Stock Exchange']

,name,summary,currency,sector,industry_group,industry,exchange,mic,market,country,...,city,zipcode,website,market_cap,isin,cusip,figi,composite_figi,shareclass_figi,delisted
symbol,,,,,,,,,,,,,,,,,,,,,
A,"Agilent Technologies, Inc.","Agilent Technologies, Inc. provides applicatio...",USD,Health Care,"Pharmaceuticals, Biotechnology & Life Sciences",Biotechnology,NYQ,XNYS,New York Stock Exchange,United States,...,Santa Clara,95051,http://www.agilent.com,Large Cap,US00846U1016,00846U101,BBG000C2V541,BBG000C2V3D6,BBG001SCTQY4,False
AA,Alcoa Corporation,"Alcoa Corporation, together with its subsidiar...",USD,Materials,Materials,Metals & Mining,NYQ,XNYS,New York Stock Exchange,United States,...,Pittsburgh,15212-5858,http://www.alcoa.com,Large Cap,US0138721065,013872106,BBG00B3T3HK5,BBG00B3T3HD3,BBG00B3T3HF1,False
AAMI,Acadian Asset Management Inc. Common Stock,Acadian Asset Management Inc. is a global inve...,USD,Financials,Diversified Financials,Capital Markets,NYQ,XNYS,New York Stock Exchange,United Kingdom,...,NaN,NaN,NaN,Small Cap,NaN,10948W103,BBG00P2HLNY3,BBG00P2HLNY3,BBG00P2HLNZ2,False
AAP,"Advance Auto Parts, Inc.","Advance Auto Parts, Inc. provides automotive r...",USD,Consumer Discretionary,Retailing,Specialty Retail,NYQ,XNYS,New York Stock Exchange,United States,...,Raleigh,27604,http://www.advanceautoparts.com,Mid Cap,US00751Y1064,00751Y106,BBG000F7RFH6,BBG000F7RCJ1,BBG001SD2SB2,False
AAQC-UN,Accelerate Acquisition Corp.,Accelerate Acquisition Corp. intends to effect...,USD,Financials,Diversified Financials,Diversified Financial Services,NYQ,XNYS,New York Stock Exchange,United States,...,Short Hills,7078,http://www.xlr8ac.com,NaN,NaN,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZTS,TIS Inc.,TIS Inc. provides information technology (IT) ...,USD,Information Technology,Software & Services,IT Services,NYQ,XNYS,New York Stock Exchange,Japan,...,Tokyo,160-0023,http://www.tis.com,Large Cap,NaN,98978V103,BBG0039320N9,BBG0039320N9,BBG0039320P7,False
ZVIA,Zevia PBC Class A Common Stock,Zevia PBC is a beverage company that produces ...,USD,Consumer Staples,Food & Staples Retailing,Food & Staples Retailing,NYQ,XNYS,New York Stock Exchange,United States,...,NaN,NaN,NaN,Micro Cap,NaN,98955K104,BBG011S2NX76,BBG011S2NX76,BBG011S2NY29,False
ZVV,NaN,NaN,USD,NaN,NaN,NaN,NYQ,XNYS,New York Stock Exchange,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
ZWS,Zurn Elkay Water Solutions Corporation Common ...,Zurn Elkay Water Solutions Corporation provide...,USD,Industrials,Transportation,Transportation Infrastructure,NYQ,XNYS,New York Stock Exchange,United States,...,NaN,NaN,NaN,Mid Cap,NaN,98983L108,BBG000H8R0N8,BBG000H8R0N8,BBG001T36GB5,False
ZYME,Zymeworks Inc.,"Zymeworks Inc., a clinical-stage biopharmaceut...",USD,Health Care,"Pharmaceuticals, Biotechnology & Life Sciences",Biotechnology,NYQ,XNYS,New York Stock Exchange,Canada,...,Vancouver,V6H 3V9,http://www.zymeworks.com,Small Cap,US98985Y1082,98985Y108,BBG019XSZ770,BBG019XSYC89,BBG019XSYC98,False